---@meta

---@class UBI_EquipDetail_C : UBUI_Widget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimUpgradeMax UWidgetAnimation
---@field AnimUpgrade UWidgetAnimation
---@field AnimDestroyed UWidgetAnimation
---@field AnimForged UWidgetAnimation
---@field AnimWeaponUnlock UWidgetAnimation
---@field ['-----------'] UWidgetAnimation
---@field AKBEquiped UWidgetAnimation
---@field AnimEquiped UWidgetAnimation
---@field ['------------'] UWidgetAnimation
---@field AKBStateSuitTxt UWidgetAnimation
---@field ['-------------'] UWidgetAnimation
---@field GSAKBDetailState UWidgetAnimation
---@field GSAKBShowHide UWidgetAnimation
---@field BI_ComplexSecRoleAttr_0 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_1 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_2 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_3 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_4 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_5 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_6 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_7 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_8 UBI_ComplexSecRoleAttr_C
---@field BI_ComplexSecRoleAttr_9 UBI_ComplexSecRoleAttr_C
---@field BI_CostItem UBI_CostItem_C
---@field BI_DetailPageSwitcher UBI_DetailPageSwitcher_C
---@field BI_EquipLongPress UBI_DetailLongPress_C
---@field BI_GearDetailBg UBI_GearDetailBg_C
---@field BI_KeyCostItem UBI_CostItemKey_C
---@field BI_ScrollInputTips UBI_ScrollInputTips_WithComb_C
---@field BI_SuitDesc UBI_SuitDesc_C
---@field BI_SuitSPDesc UBI_SuitSPDesc_C
---@field BI_UIFXDetailForged UBI_UIFXDetailForged_C
---@field ContentScroll UBI_ScrollBoxNew_C
---@field ImgLegendBg UImage
---@field ImgPageFrame UImage
---@field InputIconScroll UGSInputActionIcon
---@field MarkerForged UImage
---@field MarkerWearing UImage
---@field RetainerMaskSuitDesc UGSRetainerBox
---@field Spline UImage
---@field TxtLegendDesc URichTextBlock
---@field TxtNameRuby UGSRichScaleText
---@field UIFX_CurForge UImage
---@field UIFX_CurForgeManual UImage
---@field SparkLifeTime FVector2D
---@field SparkSize float
UBI_EquipDetail_C = {}

function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_10() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_9() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_8() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_7() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_6() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_5() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_4() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_3() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_2() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_1() end
function UBI_EquipDetail_C:SequenceEvent__ENTRYPOINTBI_EquipDetail_0() end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Play_Top(NGForgeSpark_Top) end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Stop_Top(NGForgeSpark_Top) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Play_Left(NGForgeSpark_Left) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Play_Right(NGForgeSpark_Right) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Stop_Left(NGForgeSpark_Left) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Stop_Right(NGForgeSpark_Right) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Play_Destroyed(UINS_DestroyedSpark) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_EquipDetail_C:SeqFX_Stop_Destroyed(UINS_DestroyedSpark) end
---@param EventName FString
function UBI_EquipDetail_C:SeqEvent_AnimForged(EventName) end
function UBI_EquipDetail_C:SeqAnim_DetailBg_Equiped() end
function UBI_EquipDetail_C:SeqAnim_DetailBg_Forged() end
function UBI_EquipDetail_C:SeqAnim_DetailBg_Destroy() end
function UBI_EquipDetail_C:SeqAnim_DetailBg_Upgrade() end
---@param EventName FString
function UBI_EquipDetail_C:SeqEvent_AnimWeaponUnlock(EventName) end
---@param NewParam FString
function UBI_EquipDetail_C:SeqEvent_AnimUpgradeMax(NewParam) end
---@param IsDesignTime boolean
function UBI_EquipDetail_C:PreConstruct(IsDesignTime) end
---@param EntryPoint int32
function UBI_EquipDetail_C:ExecuteUbergraph_BI_EquipDetail(EntryPoint) end


