---@meta

---@class UBI_UIFXDetailForged_C : UBUI_Widget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field _Bup_AnimDestroyed UWidgetAnimation
---@field AnimDestroyed UWidgetAnimation
---@field AnimForged UWidgetAnimation
---@field AnimUpgrade UWidgetAnimation
---@field UIFX_DestroyedMask UImage
---@field UIFX_Forged UImage
---@field UING_ForgeSpark_Left UNiagaraSystemWidget
---@field UING_ForgeSpark_Right UNiagaraSystemWidget
---@field UING_ForgeSpark_Top UNiagaraSystemWidget
---@field UINS_DestroyedSpark UNiagaraSystemWidget
---@field SparkLifeTime FVector2D
---@field SparkSize float
UBI_UIFXDetailForged_C = {}

---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_17(UINS_DestroyedSpark) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_16(UINS_DestroyedSpark) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_15(UINS_DestroyedSpark) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_14(NGForgeSpark_Left) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_13(NGForgeSpark_Left) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_12(NGForgeSpark_Right) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_11(NGForgeSpark_Right) end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_10(NGForgeSpark_Top) end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_9(NGForgeSpark_Top) end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_8(NGForgeSpark_Top) end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_7(NGForgeSpark_Top) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_6(NGForgeSpark_Right) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_5(NGForgeSpark_Right) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_4(NGForgeSpark_Left) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_3(NGForgeSpark_Left) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_2(UINS_DestroyedSpark) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_1(UINS_DestroyedSpark) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SequenceEvent__ENTRYPOINTBI_UIFXDetailForged_0(UINS_DestroyedSpark) end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Play_Top(NGForgeSpark_Top) end
---@param NGForgeSpark_Top UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Stop_Top(NGForgeSpark_Top) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Play_Left(NGForgeSpark_Left) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Play_Right(NGForgeSpark_Right) end
---@param NGForgeSpark_Left UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Stop_Left(NGForgeSpark_Left) end
---@param NGForgeSpark_Right UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Stop_Right(NGForgeSpark_Right) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Play_Destroyed(UINS_DestroyedSpark) end
---@param UINS_DestroyedSpark UNiagaraSystemWidget
function UBI_UIFXDetailForged_C:SeqFX_Stop_Destroyed(UINS_DestroyedSpark) end
function UBI_UIFXDetailForged_C:EventAnim_Forged_Play() end
function UBI_UIFXDetailForged_C:EventAnim_Forged_Stop() end
function UBI_UIFXDetailForged_C:EventAnim_Upgrade_Play() end
function UBI_UIFXDetailForged_C:EventAnim_Upgrade_Stop() end
function UBI_UIFXDetailForged_C:EventAnim_Destroyed_Play() end
function UBI_UIFXDetailForged_C:EventAnim_Destroyed_Stop() end
---@param IsDesignTime boolean
function UBI_UIFXDetailForged_C:PreConstruct(IsDesignTime) end
---@param EntryPoint int32
function UBI_UIFXDetailForged_C:ExecuteUbergraph_BI_UIFXDetailForged(EntryPoint) end


