---@meta

---@class UBUI_EquipMain_C : UBUI_Widget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimSubShowHide_0 UWidgetAnimation
---@field _Test_AnimShowHide UWidgetAnimation
---@field ['-----------'] UWidgetAnimation
---@field AKBSlotTitle UWidgetAnimation
---@field ['------------'] UWidgetAnimation
---@field AnimRefreshSubTab UWidgetAnimation
---@field GSAKBStatePageEquip UWidgetAnimation
---@field GSAKBStatePage UWidgetAnimation
---@field ['-------------'] UWidgetAnimation
---@field AnimObsMode UWidgetAnimation
---@field AnimSubShowHide UWidgetAnimation
---@field AnimShowHide UWidgetAnimation
---@field BarEquipTitle UImage
---@field BarHuluTitle UImage
---@field BarJewelryRedpoint UImage
---@field BarJewelryTitle UImage
---@field BarQuickItemTitle UImage
---@field BgEquip UImage
---@field BI_CommSubTab UBI_CommSubTab_C
---@field BI_EquipDetailCompare UBI_EquipDetailCompare_C
---@field BI_EquipQuickSlot UBI_EquipQuickSlot_C
---@field BI_EquipSlotItem_1 UBI_EquipItem_Slot_C
---@field BI_EquipSlotItem_2 UBI_EquipItem_Slot_C
---@field BI_EquipSlotItem_3 UBI_EquipItem_Slot_C
---@field BI_EquipSlotItem_4 UBI_EquipItem_Slot_C
---@field BI_EquipSlotItem_5 UBI_EquipItem_Slot_C
---@field BI_EquipSlotItem_6 UBI_EquipItem_Slot_C
---@field BI_EquipSlotItem_7 UBI_EquipItem_RZDSlot_C
---@field BI_EquipSlotItem_8 UBI_GearItem_Slot_C
---@field BI_EquipSlotItem_9 UBI_GearItem_Slot_C
---@field BI_EquipSlotItem_10 UBI_GearItem_Slot_C
---@field BI_EquipSlotItem_11 UBI_GearItem_Slot_C
---@field BI_EquipSlotItem_12 UBI_GearItem_Slot_C
---@field BI_EquipSlotItem_13 UBI_GearItem_Slot_C
---@field BI_HuluDetail UBI_HuluDetail_C
---@field BI_InputRoot UBI_InputRoot_C
---@field BI_ItemStory UBI_ItemStory_C
---@field BI_JewelryDetail UBI_JewelryDetail_C
---@field BI_JewelrySlotDetail UBI_JewelrySlotDetail_C
---@field BI_RoleAttr UBI_RoleAttr_V3_C
---@field BI_RZDDetail UBI_RZDDetail_C
---@field BI_Sorting UBI_Sorting_C
---@field BI_SubTabJewelry UBI_SubTabJewelry_C
---@field BI_TileView UBI_TileView_C
---@field BI_TreasureDetail UBI_TreasureDetail_C
---@field DebugCover UImage
---@field ImgBg UImage
---@field ListMask UGSRetainerBox
---@field MarkerJewelry UImage
---@field MarkerSlotType UImage
---@field SubTitleBar UImage
---@field TxtEquipTitleRuby UGSRichScaleText
---@field TxtHuluTitleRuby UGSRichScaleText
---@field TxtJewelryTitleRuby UGSRichScaleText
---@field TxtQuickItemTitleRuby UGSRichScaleText
UBUI_EquipMain_C = {}

function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_10() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_9() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_8() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_7() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_6() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_5() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_4() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_3() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_2() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_1() end
function UBUI_EquipMain_C:SequenceEvent__ENTRYPOINTBUI_EquipMain_0() end
---@param Navigation EUINavigation
---@return UWidget
function UBUI_EquipMain_C:DoCustomNavigation_0(Navigation) end
function UBUI_EquipMain_C:SeqAnim_Show() end
function UBUI_EquipMain_C:SeqAnim_Hide() end
function UBUI_EquipMain_C:SeqAnim_ObsUnfold() end
function UBUI_EquipMain_C:SeqAnim_ObsFold() end
function UBUI_EquipMain_C:SeqAnim_SubShow() end
function UBUI_EquipMain_C:SeqAnim_SubHide() end
---@param EventName FString
function UBUI_EquipMain_C:SeqEvent_AnimObsMode(EventName) end
function UBUI_EquipMain_C:DebugShow() end
function UBUI_EquipMain_C:DebugHide() end
function UBUI_EquipMain_C:DebugShowSub() end
function UBUI_EquipMain_C:DebugHideSub() end
---@param EntryPoint int32
function UBUI_EquipMain_C:ExecuteUbergraph_BUI_EquipMain(EntryPoint) end


